---
# This playbook builds a LAMP stack

# - name: apply common configuration to all nodes
#   hosts: all
#   user: vagrant
#
#   roles:
#     - common
#
# - name: configure and deploy the webservers
#   hosts: webservers
#   user: vagrant
#
#   roles:
#     - web

- name: nginx installation
  hosts: all
  user: vagrant

  roles:
    - nginx

- name: deploy MySQL and PostgreSQL and configure the databases
  hosts: dbservers
  user: vagrant

  roles:
    - db

# - name: add and setup users
#   hosts: all
#   user: vagrant
#
#   roles:
#     - user

- name: go install :3000
  hosts: all
  user: vagrant

  roles:
    - go_app
