---
# This playbook builds a LAMP stack

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: configure and deploy the webservers
  hosts: webservers
  user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: root

  roles:
    - db

# @pierot -> voor later, maar hier `all` zetten bij hosts
# zou slecht kunnen zijn of ook niet, ik leg dan eens verder uit.
# Maar nu neem ik `webservers`
- name: add and setup users
  hosts: webservers
  user: root

  roles:
    - role: user
      with_items: users
