---
# This playbook builds a LAMP stack

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

# - name: configure and deploy the webservers
#   hosts: webservers
#   user: root
#
#   roles:
#     - web
#
# - name: deploy MySQL and configure the databases
#   hosts: dbservers
#   user: root
#
#   roles:
#     - db
