---

- name: clone the proximity vim repo
  git: repo=git://github.com/proximitybbdo/vim.git dest=/home/{{user}}/.vim update=no

- name: set the correct owner
  file: path=/home/{{user}}/.vim owner={{user}} group={{group}} mode=0755 state=directory

# - name: install the custom vim setup
#   command: /home/{{user}}/.vim/install creates=/home/{{user}}/.vim/.vim-installed
#   sudo_user: "{{user}}"
