---
# These tasks install apache, php and php apache modules
# as described on https://wiki.archlinux.org/index.php/LAMP

- name: install apache, php and php-apache
  pacman: name={{ item }} state=installed
  with_items:
   - apache
   - php
   - php-apache

- name: apache service state
  service: name=httpd state=started enabled=yes

- name: setup apache httpd conf
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart apache

- name: setup php.ini
  copy: src=php.ini dest=/etc/php/php.ini

- name: add mimetype for php
  lineinfile: dest=/etc/httpd/conf/mime.types regexp="^application/x-httpd-php" line="application/x-httpd-php php php5" state=present

- name: set host
  lineinfile: dest=/etc/hosts regexp=localhost line="127.0.0.1 localhost leroy" state=present

- name: create the main index.php file
  template: src=index.php.j2 dest=/srv/http/index.php mode=0755

- name: make the /home folder accessible for apache
  action: file path=/home group=admin mode=0755 state=directory recurse=no

  # move the `admin` into a main vars file, because the webserver_group is used in several places

- name: install grunt (global)
  action: command npm install -g grunt-cli
