---
# These tasks install apache, php and php apache modules
# as described on https://wiki.archlinux.org/index.php/LAMP

- name: install apache, php and php-apache
  pacman: name={{ item }} state=installed
  with_items:
   - apache
   - php
   - php-apache

- name: apache service state
  service: name=httpd state=started enabled=yes

- name: setup apache httpd conf
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf

- name: create the index.php file
  template: src=index.php.j2 dest=/srv/http/index.php mode=0755

- name: install node
pacman: name=node state=installed
