---

- name: create user
  action: user name={{user}} group={{group}} shell=/usr/bin/zsh

- name: add public key to authorized keys
  authorized_key: user={{user}} key="{{item}}" path="/home/{{user}}/.ssh/.authorized_keys"
  with_file:
    - ssh_keys/{{user}}
  notify:
    - restart sshd

- include: ohmyzsh.yml homedir=/home/{{user}}
