---

- name: install docker
  pacman: name=docker state=installed
  sudo: yes

- name: start docker
  command: systemctl start docker

- name: start docker on boot
  command: systemctl enable docker

- name: enable ipv4 packer forwarding for docker
  command: sysctl net.ipv4.ip_forward=1

- name: add sysctl.d/docker.conf file
  copy: src=sysctl.d.docker.conf dest=/etc/sysctl.d/docker.conf
