---

- name: import iptable rules
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules
  notify: restart iptables

- name: sudoers
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

- name: sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: sshd_config banner
  copy: src=sshd_issue.net dest=/etc/issue.net
  notify: restart sshd

- name: update pacman
  action: command pacman -Syy

- name: set server locale
  file: src=/usr/share/zoneinfo/Europe/Brussels dest=/etc/localtime state=link

- name: install packages
  pacman: name=$item state=installed
  sudo: yes
  with_items:
    - git
    - zsh
    - git-core
    - tmux
    - wget
    - ruby
    - nodejs
    - mesa-libgl # dependency of gvim
    - gvim # has python, ruby and lua support
    - the_silver_searcher # ack, but faster
    - docker

- name: create admin group
  action: group name=admin

- include: docker.yml
