---

- name: import iptable rules
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules
  notify: restart iptables

- name: sudoers
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

- name: sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: sshd_config banner
  copy: src=sshd_issue.net dest=/etc/issue.net
  notify: restart sshd

- name: set server locale
  file: src=/usr/share/zoneinfo/Europe/Brussels dest=/etc/localtime state=link

# Use this when bug is fixed: https://github.com/ansible/ansible/issues/5679
# # After adding this you need to update the pacman database (pacman -Syy)
# - name: Add yaourt pacman destination
#   lineinfile:
#     dest=/etc/pacman.conf
#     regexp="^\[archlinuxfr\]"
#     insertafter=EOF
#     line='[archlinuxfr]\nSigLevel = Never\nServer = http://repo.archlinux.fr/$arch'
#     state=present
#     create=True

- name: Add yaourt pacman destination
  lineinfile:
    dest=/etc/pacman.conf
    regexp="^\[archlinuxfr\]"
    insertafter=EOF
    line='[archlinuxfr]'
    state=present
    create=True

- name: Add yaourt pacman destination
  lineinfile:
    dest=/etc/pacman.conf
    regexp="^SigLevel ="
    insertafter=EOF
    line='SigLevel = Never'
    state=present
    create=True

- name: Add yaourt pacman destination
  lineinfile:
    dest=/etc/pacman.conf
    regexp="^Server ="
    insertafter=EOF
    line='Server = http://repo.archlinux.fr/$arch'
    state=present
    create=True

- name: update pacman
  action: command pacman -Syy

- name: install packages
  pacman: name={{ item }} state=installed
  sudo: yes
  with_items:
    - dnsutils
    - git
    - zsh
    - git-core
    - tmux
    - wget
    - ruby
    - nodejs
    - unzip
    - yaourt # install community packages
    - htop # better top :)
    - iotop
    - mesa-libgl # dependency of gvim
    - gvim # has python, ruby and lua support
    - the_silver_searcher # ack, but faster

- name: install ntpd for date / time sync
  pacman: name=ntp state=installed
  sudo: yes

- name: ntpd service state
  service: name=ntpd state=started enabled=yes

- name: install fail2ban for ssh security
  pacman: name=fail2ban state=installed
  sudo: yes

- name: fail2ban service state
  service: name=fail2ban state=started enabled=yes

- name: create admin group
  action: group name=admin

- include: docker.yml

- include: golang.yml
