---

- name: import iptable rules
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules
  notify: restart iptables

- name: update pacman
  action: command pacman -Syy

- name: set server locale
  file: src=/usr/share/zoneinfo/Europe/Brussels dest=/etc/localtime state=link

- name: install git and zsh
  pacman: name=$item state=installed
  sudo: yes
  with_items:
    - git
    - zsh
    - git-core

- name: create admin group
  action: group name=admin

- include: add_user.yml user={{item}} group=admin
  with_items: users

- name: copy sshd config
  action: template src=/sshd_config.j2 dest=/etc/ssh/ssdh_config

