---

- name: import iptable rules
  copy: src=iptables.rules dest=/etc/iptables/iptables.rules
  notify: restart iptables

- name: set sudoers file
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

- name: update pacman
  action: command pacman -Syy

- name: set server locale
  file: src=/usr/share/zoneinfo/Europe/Brussels dest=/etc/localtime state=link

- name: install packages
  pacman: name=$item state=installed
  sudo: yes
  with_items:
    - git
    - zsh
    - git-core
    - vim
    - tmux
    - wget
    - ruby
    - the_silver_searcher # ack, but faster

- name: create admin group
  action: group name=admin

- include: add_user.yml
    user={{item.name}}
    group={{item.group}}
    groups={{item.groups}}
    password={{item.password}}
  with_items: users
